seed: 42
device: 'cuda' #(cpu)

data:
  base_dir: "/home/weed/Music/road_segmentation_test/Satellite_Datasets"
  dataset_name: "TGRS_Road"

training:
  batch_size: 1
  num_epochs: 5
#  model_path: "model/model_mc_DLv3+.pt" #Thay đổi tên với mỗi mô hình
#  plot_dir: "plot/plots_mc_DLv3+"      #Thay đổi tên chứa plot

model:
  name: "EfficientViT-Seg" #DeepLabV3Plus, Unet, FPN, DeepLabV3, LinkNet, UNet++, DPT, SegFormer, MAnet, PAN, UPerNet, PSPNet, EfficientViT-Seg

  in_channels: 3
  classes: 2
  
  encoder_name: "mobileone_s0" # resnet18, resnet50, vgg11, vgg13, densenet121, densenet169, efficientnet-b1,b2,b3, mobileone_s0,s1,s2,s3,s4
  encoder_weights: "imagenet"
  activation: null

  efficientvit_params:
    model_zoo_name: "efficientvit-seg-l1-ade20k"
    pretrained_seg_weights: "/home/weed/Music/road_segmentation_test/assets/efficientvit_seg/efficientvit_seg_l1_ade20k.pt"

overplay:
  model_path: Result\DeepGlobal\DeepLabV3Plus\model\model_DeepGlobal_CrossEntropyLoss_DeepLabV3Plus_mobileone_s0.pt

# Các lựa chọn: CombinedLoss, DiceLoss, JaccardLoss, BCEWithLogitsLoss, FocalLoss, CrossEntropyLoss
loss:
  name: "CrossEntropyLoss"
  #Nếu dùng loss ngoài CombinedLoss thì comment lại 3 dòng dưới
#  params:
#    weight_bce: 0.5   # Tham số này chỉ dùng cho CombinedLoss
#    weight_dice: 0.5  # Tham số này chỉ dùng cho CombinedLoss

optimizer:
  name: "Adam"
  lr: 0.001

scheduler:
  name: "ReduceLROnPlateau"
  params:
    mode: 'min'
    factor: 0.1
    patience: 5
